### ISSUE TITLE
AppImage, Flatpak, or Snap

### ISSUE THREAD

**Issue by zsoltsandor** [Fedict/eid-mw#113]
I am about to install openSUSE Tumbleweed for someone (I will manage updates remotely), and I found that there is support only for the numbered release versions of openSUSE.
A solution for many unsupported distros and releases could be a distro-agnostic package, like AppImage, Flatpak, or Snap. It would be nice to be able to install the software on all the distros.

**Comment by yoe** [comment]
As I understand it (but feel free to correct me with a pointer to the relevant documentation if I am wrong), unfortunately such packages all do sandboxing of the applications that they ship, which means that the package can't write to standard locations (such as /usr/lib/mozilla/pkcs11-modules), which the eID middleware requires.

It would technically be possible to create such a package for just the eID viewer and not the middleware, but that would not be very useful, in our opinion.

Since we can't actually do this, closing this (otherwise relevant) feature request.
