### ISSUE TITLE
#ifdef WIN32 is used for MSVC specific constructs

### ISSUE THREAD

**Issue by erikjanss** [Fedict/eid-mw#177]
in : 

cardcomm/pkcs11/src/common/util.cpp line 66

'#ifdef WIN32 ' is used to handle a difference between the MSVC standard library and the GCC standard library.

this prevents the use of the GCC standard library on windows, and prevents compilation of the pkcs11 plugin with mingw

**Comment by yoe** [comment]
Yeah, we should probably use defines that are based on the compiler name, rather than the platform name, for library differences, although platform differences should obviously be kept in.

We don't really have time to work on that though, so if you have patches, and they're sensible, that's definitely welcome.

**Comment by erikjanss** [comment]
I'll create a PR for this ...

**Comment by erikjanss** [comment]
PR created, using this code a working pkcs11 plugin can be compiled with mingw (with manual compilation)

**Comment by Frederikus** [comment]
PR accepted. 
Thank you Erik
