### ISSUE TITLE
[minor] don't zip the firefox extension?

### ISSUE THREAD

**Issue by pirate486743186** [Fedict/eid-mw#192]
In Debian, you can install as a deb package some firefox extensions, like for example ublock origin. I noticed that their  extensions are folders. Same position, same name

I'm assuming that the debian maintainers know what they are doing. Maybe you should just install the extension as a folder instead of the renamed zip archive. I'm assuming they do this for faster startup.

**Comment by yoe** [comment]
Doing so invalidates the signature on the extension. That's fine on Debian, where verification for extensions that are installed on the system has been disabled, but we build packages for more than just Debian and so we can't assume that that is always right. Special-casing the .deb build for what is essentially a cosmetic issue seems like something that will cause more issues than it solves, so, not going to do this.

**Comment by yoe** [comment]
It is disabled in that you don't get an error if the extension is into the system path (as opposed to your home directory), you don't get an error message if the signature is absent.

The startup time is not going to change significantly because we have to unzip one small file, which makes this mostly cosmetic. Because unzipped extensions are not supported on all distributions that we support, it would require more effort from our side for very little benefit. So this is not going to happen.
