### ISSUE TITLE
SEC_ERROR_PKCS11_GENERAL_ERROR

### ISSUE THREAD

**Issue by silenius** [Fedict/eid-mw#210]
Hello,

I'm unable to authenticate with my identity card, I'm getting the following message:

```
Secure Connection Failed

An error occurred during a connection to certif.iamfas.belgium.be. A PKCS #11 module returned CKR_GENERAL_ERROR, indicating that an unrecoverable error has occurred.

Error code: SEC_ERROR_PKCS11_GENERAL_ERROR
```

The environment is: Firefox 130.0 with the "eID Belgium" extension (1.0.32) running under FreeBSD 14.1. pcscd is running and I can read the data with the `eid-viewer` tool so i guess the issue is with the Firefox plugin. In the past the plugin used the `pinentry` tool to enter the password but apparently it doesn't work anymore

**Comment by yoe** [comment]
This error is the CKR_GENERAL_ERROR one that the PKCS#11 library returns, which is an error that is thrown when no more specific error condition is available. This can be pretty much anything; examples from the past have included faulty cards, incorrect PC/SC drivers, or software misconfigurations such as the absence of pinentry on the system.

In order to know which of these is happening, more information is needed. I recommend you contact the BOSA helpdesk through https://eid.belgium.be/en/contact, who will be happy to help you figure out the actual problem here.

Closing this bug report, as it is difficult to see with the information on hand whether there is an actual bug here. If further investigation shows that there is a problem, we can always reopen.
