### ISSUE TITLE
4.2.11: eid-viewer logo is missing

### ISSUE THREAD

**Issue by kyrios123** [Fedict/eid-mw#49]
I just compiled eid-viewer 4.2.11 on linux 64-bit and the eid-viewer.png logo is used by the .desktop file is not installed anymore.

**Comment by yoe** [comment]
pushed a commit that fixes this problem on the v4.2 branch.

Please note though that even though tags exist on the v4.2 branch beyond the currently-released version 4.2.5, none of those tags were tested on Linux. Since our team is rather small, testing all tags on all platforms would require unreasonable development time; therefore, a tag is usually applicable to one platform only, rather than to all platforms.

In the case of Linux, the most recent supported tag is v4.2.5. All more recent ones are not released yet.

With this change, I'll probably make a new release for Linux soon, once I've confirmed that the changes work as expected.

**Comment by kyrios123** [comment]
Thanks @yoe !
Good to know, will be less packaging work for me as well ! 😃 
It would be nice to add a comment when a release is done or tagged to say which platform is concerned (or at least to do it when a the release has been tested against a non-windows platform).

**Comment by kyrios123** [comment]
Hi!
Just a short message to thank you, @yoe for adding the OS when you tag a release.
This is much easier for the packagers, really appreciated !
