### ISSUE TITLE
Can you verify a signature with an eID card?

### ISSUE THREAD

**Issue by cimm** [Fedict/eid-mw#61]
I think I managed to sign a message using the [graphene](https://github.com/PeculiarVentures/graphene) library and my eID card:

```js
var graphene = require("graphene-pk11")
var Module = graphene.Module
var lib = "/usr/lib/x86_64-linux-gnu/libbeidpkcs11.so.0"
var mod = Module.load(lib, "eID")
mod.initialize()
var session = mod.getSlots(0).open()

var privateKey = session.find({class:graphene.ObjectClass.PRIVATE_KEY}).items(1)
var sign = session.createSign("SHA1_RSA_PKCS", privateKey)
sign.update("Hello World")
console.log(sign.final().toString("hex"))

var publicKey = session.find({class:graphene.ObjectClass.PUBLIC_KEY}).items(1)
var verify = session.createVerify("SHA1_RSA_PKCS", publicKey)
verify.update("Hello World")
console.log(verify.final(signature))

session.logout()
session.close()
mod.finalize()
```

The first `console.log` prints the signature for the "Hello World" message, so far so good, I think. It uses the private key of the "Signature" certificate as explained in the [wiki](https://github.com/fedict/eid-mw/wiki/Development#digitally-signing-data-with-the-card).

The verification part fails: `CKR_FUNCTION_NOT_SUPPORTED`.

Am I doing something wrong or does the Belgian eID card not support verification of a signed message?

I am trying to understand if the signature above counts as a legal signature. Do I simply add that signature to the document to prove it was signed, like one signs a document with pen and paper?

**Comment by yoe** [comment]
Correct, verification is not supported by the eID middleware. We could theoretically implement that as a software-only thing, but since we're not a crypto accelerator, that seems fairly pointless (there are loads of general-purpose crypto libraries that could do so instead).

If you need some inspiration, you could look at [the test suite](https://github.com/Fedict/eid-mw/blob/master/tests/unit/sign.c#L63-L85), where we use OpenSSL to verify a signature from the card.

Having said that, unless you are a cryptographer and your code is peer-reviewed, I do not recommend that you implement your own signing algorithm at that level. If you need to sign a document, it is usually preferable that you use a library written to sign and/or verify signatures on the type of documents you wish to sign. Most of those libraries allow you to point to PKCS#11 modules, too; the PKCS#11 standard is pretty widely implemented. There is too much that can go wrong otherwise, and then the legality and/or validity of your signature are questionable.
