### ISSUE TITLE
DnD functionality

### ISSUE THREAD

**Issue by qlecler** [Fedict/eid-mw#84]
Hello there,

`// Did the user drop a file, or drag data out of the eID-Viewer?
		// NOTE: the necessary changes to the eID-Viewer to
		// support this (without saving a file and dropping that
		// out of a file manager) have not yet been released,
		// and won't be until after tax-on-web.`

[dnd.html](https://github.com/Fedict/eid-viewer/blob/master/xml/dnd.html)

Latest version doesn't seems to have this functionality yet.

Any chance it'll be implemented in the near future?

If not, would there be another web solution (no third party services, no java) to get the information from the card.

Thanks 👍

**Comment by Frederikus** [comment]
Hello,

There was indeed a bug in the DnD functionality of the eID Viewer, it is fixed in the current beta download of the windows viewer. It has also been fixed in the mac Viewer, but that one hasn't been released yet (to be expected this month).
For the linux Viewer I should check with Wouter, but I'm not aware of any DnD issues there atm.

**Comment by qlecler** [comment]
In the meantime, would there be another way ?

I've heard of :

[https://github.com/Trust1Team/t1c-lib-js](https://github.com/Trust1Team/t1c-lib-js)

**Comment by Frederikus** [comment]
We've put eID Viewer 4.4.16 for macOS online as future release
(https://eid.belgium.be/en/future-versions-eid-software-and-eid-viewer)

This one has had the DnD feature fixed (dragging the photo into e.g. a text editor)
